server:
  port : 8080

swagger:
  host:
    url: http://localhost:8080


fieldsRestrictions:
  vacancyMin: 5
  vacancyMax: 100

  cityMin: 3
  cityMax: 100

  companyMin: 3
  companyMax: 100
# ===============================
# JPA / HIBERNATE
# ===============================
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ratethem?serverTimezone=UTC&useSSL=false&characterEncoding=UTF-8
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect


#Logging Levels by Package
logging:
  level:
    co.ratethem: DEBUG
    org.springframework: INFO